-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.songs
(
    id serial NOT NULL,
    "group" text COLLATE pg_catalog."default",
    name text COLLATE pg_catalog."default",
    releasedate text COLLATE pg_catalog."default",
    text text COLLATE pg_catalog."default",
    link text COLLATE pg_catalog."default",
    CONSTRAINT songs_pkey PRIMARY KEY (id)
);
END;